### ISSUE TITLE
Last.FM support

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#116]

**Comment by rhubarbselleven** [comment]
:heart:  :+1:

**Comment by johniejohn** [comment]
:thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup: :thumbsup:

**Comment by pablasso** [comment]
"Very distant future" :(

**Comment by kkamperschroer** [comment]
Hey. I own a slightly different extension called Musicality. It's also open source and I wrote in scrobbling functionality. Feel free to pull in whatever pieces of my code you need from here:

https://github.com/kkamperschroer/Musicality/blob/master/js/background/scrobbler.js

**Comment by RockyMM** [comment]
@kkamperschroer Excellent! :+1: I took a quick glance at your code, looks rather neat. ;) I don't have any experience with Chrome extensions nor the time to learn, so I hope that somebody will use this piece of code for a rather soon-ish pull request :)

**Comment by inem** [comment]
+1

**Comment by DanPantry** [comment]
I'm looking into this now though I can't promise anything as I don't really contribute to OSS as much as I'd like and I've never used Backbone (I'm an Angular man). However, here's the relevant docs

- Need to authenticate with Last.FM first. This follows a typical OAuth flow - info [here](http://www.last.fm/api/webauth)
- After authenticating with Last FM, session key, api signature and api key are retrieved, these must be passed to any calls to Last.FM.
- Last.FM indicates you may only send a scrobble request if a song has been playing for at least 30 seconds and has been playing for at least half of it's duration - see [here](http://www.last.fm/api/scrobbling). They also suggest sending the request after song has finished playing; this would be easier to implement.
- Scrobble info must be POSTed to http://ws.audioscrobbler.com/2.0/. The data object must look something like this:

````js
    data: {
      artist: this.artist,
      track: this.name,
      api_key: apiKey,
      api_sig: apiSignature,
      sk: sessionKey,
      method: 'track.updateNowPlaying'
    }
````
- Responses as a bit weird, no HTTP codes, instead there are error codes, see [here](http://www.last.fm/api/show/track.updateNowPlaying). Example shows XML code but you can ask for [JSON response](http://www.last.fm/api/rest) by appending `format=json` to the end of the url querystring

I'll see if I can implement it this weekend (have my girlfriend coming over so not a 100% guarantee!) but I'll need to know how the OAuth flow should be handled - any ideas?

**Comment by xgear-public** [comment]
Thanks for awesome extension! +1 for Last FM Support.

**Comment by goranpejovic** [comment]
Only thing missing is this

**Comment by gwigz** [comment]
:+1:
