### ISSUE TITLE
Add media key support

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#118]
https://chrome.google.com/webstore/detail/swayfm-unified-music-medi/icckhjgjjompfgoiidainoapgjepncej 

Figure out how they do it and implement it

**Comment by msfeldstein** [comment]
http://sway.fm/api

**Comment by jeffzemla** [comment]
I added support for this by borrowing code from keysocket as @KoenRijpstra suggested. I'm not familiar with the frameworks you're using so you'll probably want to refactor this code.

**Comment by jeffzemla** [comment]
Oh and it's probably best to add something in the Settings menu to disable it?

**Comment by MeoMix** [comment]
I don't think that this can actually be supported. I looked through the media key things and it looks like they're just piping commands to other websites.

What I was thinking of was more like NPAPI listening to custom keyboard commands and then sending that to Streamus, but NPAPI has been discontinued for chrome extensions. I think if Chrome doesn't recognize a keyboard command then people are SOL.
