### ISSUE TITLE
Implement a normalizer

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#123]

**Comment by WooHooBar** [comment]
Dude, an extension called Audio EQ for Chrome does just this. It works seamlessly with Streamus.

**Comment by MeoMix** [comment]
Thanks for the tip! I will take a look when I can. The reviews weren't
great for it, but maybe it has some useful tips.

**Comment by roko-p** [comment]
Hey guys,

@WooHooBar I have **Audio EQ**, but it doesn't seem to affect Streamus :disappointed:
(It does affect videos played directly on Youtube) How did you get it working?

@MeoMix Does Audio EQ work with Streamus for you? (Insanely **awesome** extension by the way, a million thanks!!)

(Chrome 43.0 on Win8.1 here, if that matters)
