### ISSUE TITLE
Automatic refresh of imported YouTube playlists

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#16]
Users are able to import YouTube playlists into Streamus. They have an expectation that an imported playlist will automatically update when new songs are added to it on YouTube.

In order to do this, several things need to happen:
- The Playlist object needs another property -- 'import URL'. It might also need an 'import source' if we expect to need to update from SoundCloud vs YouTube.
- This property will need to be persisted to the database.
- The playlist will need a means of diffing its current state with the playlist known to YouTube.
- It should be able to automatically refresh on a time interval, but we must be careful not to flood with requests by staggering the interval. That is, if there are 100 imported playlists they should not all attempt to update at 12:00 PM.
- Perhaps the auto-update time should be configurable by the end user.
- The user should be able to trigger the update manually.
- Auto-updating should try its best to not restore songs which have been deleted by the user.
- (Bonus points) Show a badge on Streamus' icon indicating that the user has new songs to listen to. This would be similar to Facebook's new IM badge.

**Comment by mattbalza** [comment]
I would love that!

**Comment by Devian50** [comment]
@MeoMix, I'm a month past the most recent comment, but I think I know how you could check for new uploads at least. I'm not sure if it works for playlists as well, but uploads per channel have an RSS feed that can be read with the topmost "entry" being the most recent upload. I use it in an IFTTT recipe myself. an example of a link to one of these feeds is as follows: 
`https://gdata.youtube.com/feeds/api/users/%USERNAME%/uploads`
where `%USERNAME%` can be the channel ID or the Channel name as it appears in a `youtube.com/user/` link.

I also found [this](http://elliottbledsoe.com/brain-drain/how-to/rss-subscribe-to-youtube-playlist/) for grabbing playlists as an RSS feed.

Just leaving this here in case it helps!

**Comment by MeoMix** [comment]
Oh cool! Thanks for the information. RSS feed would probably be a decent
option. The other way to do it would be to query YouTube's API for the
given playlist and keep track of the page token for the last page
retrieved. Then, when needed, query for that page again, check for new
records and/or existence of a next page token.

The real complications involve deletions and songs added to the playlist
manually. If someone deletes a song in the playlist then it shouldn't
restore itself on update and songs which are manually added shouldn't
disappear. Not exceedingly difficult, now that I think about it, but
definitely a couple of edge cases to consider. Possibly others out there,
too.

**Comment by raine** [comment]
Simply a button under "More options" that reimports a playlist would be a good start.
