### ISSUE TITLE
Notification for videos that have the audio muted/removed due to copyright/other

### ISSUE THREAD

**Issue by NinjaBanjo** [MeoMix/StreamusChromeExtension#181]
When you add a video to the playlist that has audio muted it looks like it's playing, with no notification of the audio being muted for the video.

Is there a way to check for this and give the user a notification?

**Comment by MeoMix** [comment]
I never really found any more details on this :( And the link cited now is unmuted, so maybe the problem went away. Feel free to re-open if need be.
