### ISSUE TITLE
Mark already played songs in Playlist with different font or color

### ISSUE THREAD

**Issue by flatlinebb** [MeoMix/StreamusChromeExtension#204]
When I have a long playlist, I want to know what I already heard, it would be nice to have the already heard songs marked somehow. Maybe change the font color, or add italics.

**Comment by MeoMix** [comment]
This hasn't happened because it's a UI/UX question. I wonder what a good way to convey this information is?

Color isn't too great to rely upon because then the colorblind are SOL on this information, but I don't really want to throw an icon onto everything when it has played. Hmmm.

**Comment by Dazzel** [comment]
Make them a bit transparent?

**Comment by MeoMix** [comment]
Haven't heard this requested really at all. Going to close for now. If it becomes a big issue at some point I'll revisit it.
