### ISSUE TITLE
Muted icon + More information when interacting w/ volume icon

### ISSUE THREAD

**Issue by vikalp02** [MeoMix/StreamusChromeExtension#256]
the volume icon when pressed mutes the playback and turns red, but the indication isn't intuitive for long time. I just clicked by mistake and was thinking that why hasn't the streamus working in background while I worked.

When "mute" is activated icon the volume icon can be changed to http://iconmonstr.com/audio-5-icon/ and colored red.

**Comment by MeoMix** [comment]
Okay, new volume icon has a slash through it when muted instead of turning colors.
