### ISSUE TITLE
Re-adding previously added song when on new YT page

### ISSUE THREAD

**Issue by bcool14** [MeoMix/StreamusChromeExtension#302]
Description: Load page X, using the youtube tab to add songs to streamus, adding song A to playlist 1, success.  Load page Y, using same youtube tab to add song B, upon submission, song A is added again to said playlist. Have to manually put in URL for song B.

**Comment by MeoMix** [comment]
Thanks for the bug report, taking a look at it right now. Sorry for the delay.

**Comment by MeoMix** [comment]
Alright, simple fix. jQuery .data() was returning cached value and replacing it with .attr('data-) fixes it. It'll be in the next release.
