### ISSUE TITLE
Consider refactoring events to use obj syntax

### ISSUE THREAD

**Issue by jmeas** [MeoMix/StreamusChromeExtension#303]
[example](https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/foreground/model/clearStreamButton.js#L13-L15)

current:
```js
this.listenTo(streamItems, 'add', this._onStreamItemsAdd);
this.listenTo(streamItems, 'remove', this._onStreamItemsRemove);
this.listenTo(streamItems, 'reset', this._onStreamItemsReset);
```

suggested:
```js
this.listenTo(streamItems, {
  add: this._onStreamItemsAdd,
  remove: this._onStreamItemsRemove,
  reset: this._onStreamItemsReset
});
```

It's just preference, and although it's more lines I do like the obj syntax :cake:

And if you wanted to be super pro you could use `bindEntityEvents` and put the events right on the object.

```js
MyModel = BB.Model.extend({
  thingEvents: {
    whatever: this._onWhatever
  },

  initialize: function() {
    this.bindEntityEvents(this.thing, this.thingEvents);
  }
});
```

**Comment by MeoMix** [comment]
I did some work on this, but have some questions for you jmeas!
