### ISSUE TITLE
Scrolling bug

### ISSUE THREAD

**Issue by michael-jerred** [MeoMix/StreamusChromeExtension#307]
There is a bug when adding a song to a playlist and moving it around, when using the view in tab feature.

To reproduce:
- create a playlist with enough songs that it needs to be scrolled to see it all, I had around 50 songs.
- add a song to the playlist, so it appears at the bottom
- move that song further up in the playlist
- scroll up, and move the song higher up (as if you were trying to move it to the top)
- observe that scrolling bounces and when reaching the top of the playlist some songs have been cut off of the top

I think this is just a display issue as changing to a different playlist then back again fixes everything.

**Comment by MeoMix** [comment]
This is fixed :+1:
