### ISSUE TITLE
Allow for desktop notifications to be disabled via settings

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#320]
It's possible to disable them through Chrome Notifications Center, but I've had a lot of users get confused about that. It'd be better to provide the option through Streamus, as well.

**Comment by DynamicSeagull** [comment]
Was just looking through github to figure out how to do this. Doing it through chrome required a little digging and adding a switch or check to shut this on/off in the settings popup would be amazing. Just found this extension from reddit. Amazing work!

**Comment by MeoMix** [comment]
:D Yep! Totally understand. It's a learning process to realize what's obvious / not obvious.
