### ISSUE TITLE
Change Play button in playlist to Pause when playing specific song

### ISSUE THREAD

**Issue by augbog** [MeoMix/StreamusChromeExtension#330]
When you choose to play a specific song, it plays the song completely fine but in the playlist itself the play button remains. I know there is a main video control at the top, but it'd be better UI if the specific song you are playing in the playlist would update it's state so that you could pause from there.

If you feel this is unnecessary, feel free to close. Just thought I'd throw it in as a minor enhancement.

![screen shot 2015-01-13 at 10 14 01 am](https://cloud.githubusercontent.com/assets/2054339/5726061/47614e70-9b0d-11e4-8007-14b2ae81b096.png)

**Comment by MeoMix** [comment]
Yeah I agree, I had it on a TODO list somewhere but it got sidelined
and forgotten about. I'll look at it again

**Comment by MeoMix** [comment]
Boom, added.
