### ISSUE TITLE
Radio mode broken after latest update

### ISSUE THREAD

**Issue by SomeKittens** [MeoMix/StreamusChromeExtension#332]
Updated to latest (which also killed Chrome, thanks) and now radio won't work.  It finishes the song and stops.

**Comment by MeoMix** [comment]
Hey,

chrome.extension.reload is bugged for all extensions, not just Streamus. I removed it from the settings menu temporarily, but missed it from other reload points in Streamus. You can reproduce the issue with any extension by simply having their foreground UI open and then unchecking 'enabled' in extensions. Nothing I can do about that except wait for Google to fix it.

I agree that there's something up with Radio Mode. It should work fine if you just clear your stream of music and re-add songs. It's not pulling in the previously loaded 'related songs' array for songs which were knows to Streamus before the update. I took a look at the code, but I'm not 100% sure why. I'll revisit it when I can, but the workaround to fix it is trivial and will solve itself automatically as the new version propagates.

Hope that helps

**Comment by SomeKittens** [comment]
Ah, that makes sense.  Thanks!
