### ISSUE TITLE
UI is unresponive when trying to play large playlist

### ISSUE THREAD

**Issue by Dazzel** [MeoMix/StreamusChromeExtension#333]
The UI and the whole plugin becomes unresponive if an large playlist is selected for play now. It seems like it tries to fetch all the songs in the playlist to the current playing stream which leads into an duplicate of this playlist.

Try this channel: https://www.youtube.com/channel/UC5nc_ZtjKW1htCVZVRxlQAQ

**Comment by MeoMix** [comment]
Hey

This is probably because all the items in your stream are written to
localStorage so that they can be persisted through restarts of Streamus.

I'll try and think of a way to resolve the issue, but not immediately clear
atm

**Comment by Dazzel** [comment]
Mh.. Thats what I thought the plugin is doing. Maybe there is a way to do this in an async way or load it chunk by chunk..

**Comment by MeoMix** [comment]
Yeah, I need to see if web workers can write to localStorage.

**Comment by MeoMix** [comment]
They can't.

I think the solution here is to re-implement the Backbone.LocalStorage
adapter I'm using but write it to use chrome.storage.local which is an
asynchronous method of writing to localStorage. That's non-trivial, but not
suuuper hard either.

**Comment by hypershadsy** [comment]
*Adding* all songs from a playlist to the stream has the same issue.

**Comment by MeoMix** [comment]
Yep. It's because localStorage is a blocking mechanism. I need to
change to chrome.storage.local which is async. It's on my TODO list
for sure.

**Comment by Madgvox** [comment]
If you're not already, check out [lz-string compression](http://pieroxy.net/blog/pages/lz-string/index.html) for writing to localStorage. It saves a ton of space and is much faster to read & write than doing it raw.

**Comment by MeoMix** [comment]
Interesting. I hadn't thought about that, but I think the real issue
(I suspect?) is the actual opening/closing of localStorage. Using an
async version would solve the problem entirely (but better compression
would be good, too!)

**Comment by Madgvox** [comment]
Certainly, async is ultimately the way to go, and I'd highly recommend compressing it anyway (better to be safe than sorry). I've never heard of simply opening and closing localStorage locking up UI though, at least on the web development side. Is it much slower for extensions?

**Comment by MeoMix** [comment]
I'm using Backbone.LocalStorage adapter which makes Backbone's RESTful
calls go to localStorage instead.

When you import a playlist that has 1K songs in it I suspect it's
opening and closing localStorage 1K times to do the insert. It took my
PC about 4 seconds to process everything, but I'm sure PCs with lower
specs would perform much worse.

**Comment by Madgvox** [comment]
Ah, there's the problem. It's not the localStorage itself, it's the inefficient way the adaptor is accessing it. I would definitely roll your own localStorage adaptor that saves in bulk. You wouldn't even need to do it async if you're only making one save call per playlist, even with 1K songs (and especially if you compress it beforehand).

**Comment by MeoMix** [comment]
I do bulk saves to my server (so I do agree and I had identified it as
a problem in the past), but I just kind of threw in the logic for
streamItems because they're stored locally.

I'm a bit conflicted on whether I should stay RESTful and just be
async or have specific, bulk operations. Feels a bit odd, but maybe
necessary.

**Comment by MeoMix** [comment]
Performance is a lot better after 71b3fc39bb9434ab2d639cfcf9c1baa7ce6a9ef2. I'll open a new enhancement request for rewriting localStorage to use chrome.localStorage, though, as it'd still shave maybe 20% off the time
