### ISSUE TITLE
Message on empty queue

### ISSUE THREAD

**Issue by Dazzel** [MeoMix/StreamusChromeExtension#334]
I think the "Can't toggle song" message should not be shown if the queue is empty.

**Comment by MeoMix** [comment]
I think that some message should be shown when your keyboard shortcuts
don't have an effect. There's no UI open to convey the fact that it's not
just buffering or something, so..?

**Comment by Dazzel** [comment]
Yea sure, if something is in the queue you are absolutly right, but what if there is nothing in the queue? I mean, you obivously know there is nothing in the queue. So we do not need the message right?

**Comment by MeoMix** [comment]
Err... I mean, if you cleared your queue, went and did some things,
forgot that you cleared your queue, come back to your pc, and use a
keyboard shortcut to tell Streamus to start playing again... and
nothing happens and no music comes out... that would be weird, right?

You'd only ever see the "Can't toggle song" message when the queue is empty.

**Comment by Dazzel** [comment]
I understand your idea there. But i guess you to not need to move every responsibilty away from the user. I mean, if you cleared the queue you should know that you've done it. Take a look at every other media player.

Another thing is, when you've mapped the same shortcut e.g. the media play key to another player you always get this message, which could be very annoying.

**Comment by MeoMix** [comment]
Is the same keyboard shortcut able to be mapped to multiple players? I
figured Chrome would consume the shortcut, but maybe not! Hadn't tried that.

**Comment by Dazzel** [comment]
It is possible to map an key to multiple players.
Also I use for example Google play music and Pandora with an plugin called
streamkeys. So pausing / starting in song in one of these with the same
keyboard shortcut toggles the message.
Am 16.01.2015 18:37 schrieb "Sean Anderson" <notifications@github.com>:

**Comment by MeoMix** [comment]
Eh, I guess I just disagree. There's a lot of odd problems that will happen if you map the same key to multiple programs. If I hit 'play' and nothing plays then I want a warning. You can disable notifications entirely if they're interfering with your workflow and I think that's sufficient.
