### ISSUE TITLE
Playlist search cleared

### ISSUE THREAD

**Issue by danbaugher** [MeoMix/StreamusChromeExtension#337]
When selecting songs from a search display the selected items are cleared after clicking the save button at the bottom of the search display. If a playlist is clicked after clicking save the selected songs that were cleared are not added to the playlist.

**Comment by MeoMix** [comment]
I can reproduce this, thanks for the bug report.

I'll have it fixed in the next rev.

**Comment by danbaugher** [comment]
Thumbs up for the quick fix. I was working a screencast to add here. 

Found you on reddit, keep up the great work on an awesome project.

**Comment by MeoMix** [comment]
This was fixed, but I'm also changing the UX for selections so that they don't de-select so willy nilly.
