### ISSUE TITLE
Add an equalizer

### ISSUE THREAD

**Issue by bruno-cintra** [MeoMix/StreamusChromeExtension#340]
My speakers are too bassy so I use an EQ extension to fix this (http://lab.ejci.net/Chrome-Audio-EQ/). When I use streamus it is unnaffected by the EQ extension and I can't fix my speakers unbalaced bass.

**Comment by MeoMix** [comment]
I'm not allowed to modify the sound of YouTube videos except through YouTube's API (aka muting / volume).
