### ISSUE TITLE
Ability to import existing youtube playlists?

### ISSUE THREAD

**Issue by awesomeyi** [MeoMix/StreamusChromeExtension#341]
Currently, there doesn't seem to be a way to import existing youtube playlists.

**Comment by pittofdirk** [comment]
From [Getting Started](https://streamus.com/#getting-started):

***Adding playlists***
The playlist management pane can be expanded by clicking the button located in the upper-left corner. You can add, delete and rename playlists from here. When adding a playlist -- **you may provide a YouTube channel or playlist URL as a source**. In the future, you will be able to login to YouTube and access personal playlists as well as SoundCloud and other services.

**Comment by MeoMix** [comment]
I think this needs to be made more visible somehow. A lot of users are
confused about how to do this, but it's literally the only option I
hide away.. How can I make it more obvious?

**Comment by awesomeyi** [comment]
This is a suggestion:
![image](https://cloud.githubusercontent.com/assets/4894854/5812228/7cdd4aba-a033-11e4-9e0d-b9b0fe7ca80a.png)
Add it to the empty playlists page.

**Comment by MeoMix** [comment]
Mmm yeah, I could see that. Maybe some text that opens the create a
playlist dialog or something. Or imports into the current playlist.

**Comment by MeoMix** [comment]
I think I'm going to close this in favor of #352
