### ISSUE TITLE
Speed up window display when Streamus icon is clicked

### ISSUE THREAD

**Issue by pittofdirk** [MeoMix/StreamusChromeExtension#342]
0 sec: Icon clicked
.5 sec: Window displays blank white
1.2 sec: Window displays all content

timing is estimated, not measured.

**Comment by MeoMix** [comment]
I've already taken a pretty marked improvement on this with the recent
update to Marionette. They introduced an onAttach method which allows
me to render earlier and hopefully speed this up.

If you're still experiencing issues in the next version then I'd love
to see some timeline profile screenshots.

**Comment by MeoMix** [comment]
You know, I looked at this more and I have no fucking clue what's going on.

The timeline shows a pretty obvious blank spot in the loading time, but it's not like it's doing work. It's like Chrome is firing up or something... all of the load times for my views seem very reasonable.

However, I agree! I see the laggy load time. I can't help but wonder if this is just an issue on Chrome's side, but maybe it's me.

**Comment by MeoMix** [comment]
I've been digging into this more and have some ideas on how to speed it up, but it's going to take some effort. It'll increase the overall memory footprint of Streamus slightly by keeping the majority of JavaScript files parsed all the time, but allow for a more instantaneous open.

**Comment by MeoMix** [comment]
It should be opening a lot quicker in the next version. :)
