### ISSUE TITLE
Add setting to control how long "currently playing" popup lasts

### ISSUE THREAD

**Issue by pittofdirk** [MeoMix/StreamusChromeExtension#343]
It's too short to read more than a few words.

**Comment by zQueal** [comment]
Quite honestly, I think this is more of a chrome feature--and I doubt it would be able to be messed with by plugins. As of now, you can disable them altogether, or display them. There is no option to change the delay at which they are displayed. [More reading here.](https://support.google.com/chrome/answer/3220216?hl=en)

**Comment by pittofdirk** [comment]
Gotcha. If nobody says anything to the contrary I'll close this tomorrow.

**Comment by MeoMix** [comment]
The notification close timeout is indeed customizable, see here: https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/background/model/chromeNotificationsManager.js#L92

I haven't had any complaints about 3 seconds in the past, but I can consider making it customizable. It's important to question whether >20% of users would customize a setting. If not, Google suggests that you should try to make an educated guess yourself. Ref:  http://www.google.com/design/spec/patterns/settings.html#settings-settings

**Comment by zQueal** [comment]
> var closeNotificationTimeout = setTimeout(this._onCloseNotificationTimeout.bind(this), 3000);

Thanks! I had no idea that you could bind a timeout.
