### ISSUE TITLE
Keyboard shortcuts doesn't allow numbers/special char

### ISSUE THREAD

**Issue by marzim** [MeoMix/StreamusChromeExtension#346]
Keyboard shortcuts doesn't allow numbers such as Ctrl+(1-9) and special char such as Ctrl+/-+*

**Comment by MeoMix** [comment]
This isn't up to me. This is Google Chrome: 

Supported keys: A-Z, 0-9, Comma, Period, Home, End, PageUp, PageDown, Space, Insert, Delete, Arrow keys (Up, Down, Left, Right) and the Media Keys (MediaNextTrack, MediaPlayPause, MediaPrevTrack, MediaStop).

https://developer.chrome.com/extensions/commands
