### ISSUE TITLE
Touch support

### ISSUE THREAD

**Issue by EladBezalel** [MeoMix/StreamusChromeExtension#347]
Hi! great work!!

Can you add touch support for copmuters with touch screen :smile: 
Like dragging songs or get the song url or anything you could think of?

Love it,  really thank you!

**Comment by MeoMix** [comment]
Wanna buy me a cheap computer with touch screen support so I can test it? ;) 

But in all seriousness I'll give it a go, might not be perfect first time around because I legitimately can't test it without some sort of emulator, but we'll see.

**Comment by EladBezalel** [comment]
Basically the touch behave like a mouse..
Drag and drop would work with mouse gesture as well.. For other gestures I'll be happy to test for you :dance:
