### ISSUE TITLE
Change "Playlist 0000" to something more fun

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#357]
C'mon, this is Streamus awesomesauce program not a robot. What's a good name for an initial playlist?

**Comment by gaborbernat** [comment]
Simply just: awesomesauce ?

**Comment by DynamicSeagull** [comment]
"Dank Memes"

**Comment by bshah2016** [comment]
Its a bit generic but how about just "Favorite Playlist"?

**Comment by hypershadsy** [comment]
Honestly, "New Playlist". Anything too crazy could be confusing to new users.

I don't get the trend of informal language in software. It doesn't make the application any more familiar, just seems patronizing. That's just me.

**Comment by DynamicSeagull** [comment]
Seriously, I think "New Playlist" would be best. Kinda helps explain to the user what it is if that makes sense and gets them to click it.

**Comment by MeoMix** [comment]
As a counter-argument, https://www.youtube.com/watch?v=KKYkmYuk5l8&t=23m20s

I've watched this a couple of times and Alexis Ohanian can't stress enough how important it is to surprise and delight users. Especially when you're a small company. Little things can really make people happy..

Maybe this isn't the area for that, but I certainly think it's worth considering more than being drab with the title.

**Comment by silviubogan** [comment]
I vote for "My Playlist".

**Comment by JordanBlakey** [comment]
"MeoMix"? "Blank Mixtape"? "My Jams"?

**Comment by MeoMix** [comment]
I think I'm going to be lame and go with "My first playlist" :-1: but it's for the best.
