### ISSUE TITLE
media key support

### ISSUE THREAD

**Issue by gaborbernat** [MeoMix/StreamusChromeExtension#360]
Media key support, they are already some extensions that make this possible, see StreamKeys :+1:  
https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen?hl=en

**Comment by hypershadsy** [comment]
Does entering a media key into these boxes work for you?
chrome://extensions/configureCommands
Regular keys do work while media keys don't. Chrome Linux x64.

**Comment by MeoMix** [comment]
They work fine for me... http://i.imgur.com/twhiwrH.png

I'm on Win 7 64 w/ a Logitech Keyboard. The Development version of Streamus sets the ones shown in the screenshot on install as suggestions. 

Could use more info!

**Comment by hypershadsy** [comment]
Nevermind, GNOME was just eating them up, and the keypresses never got to Chrome.
http://ubuntuforums.org/showthread.php?t=2241639&p=13110153#post13110153
The media keys work great.

**Comment by MeoMix** [comment]
:+1:

**Comment by hypershadsy** [comment]
I see you closed this, and just for clarification, I'm not OP. My 
solution may not work for him, I was just stating I had fixed it on my 
end. I have no idea if he's even on the same platform as I.

**Comment by MeoMix** [comment]
I just don't think that there's any programmatic solution I can offer to improve media key support. Keyboard shortcuts are strictly handled by Chrome. I can't even set them via JavaScript, they have to be declared in the manifest.json.

Any issue with shortcuts is either a lack of support on Chrome's side or PEBKAC. :)

**Comment by gaborbernat** [comment]
Still there are plug-ins that do this, so it's possible to do it somehow :)

**Comment by MeoMix** [comment]
They're not doing anything special... you just have to go into Keyboard Shortcuts, set your keyboard shortcut to 'Global' and set the media key by pressing it.

Their extension just sets those by default with manifest.json.

**Comment by omegachysis** [comment]
I'm OP, and Media Keys are working for me too, I just jumped the gun and commented before I really looked into it carefully.
