### ISSUE TITLE
Make toolbar color match situation 

### ISSUE THREAD

**Issue by EladBezalel** [MeoMix/StreamusChromeExtension#361]
As the icon that changes according to the player state (play, pause..) maybe you should change the tool bar color to be the same :) just a thought..

**Comment by bshah2016** [comment]
I can work on creating the .svg or .png icons, if you want @MeoMix. Just let me know what you're specifically looking for.

**Comment by MeoMix** [comment]
I think that changing the color of the top bar miiiight be a bit offensive to people. Reds and yellows generally convey error state and having that shown always when paused is meh.

People have been asking to be able to custom theme their Streamus quite frequently. Dark/night mode, disable the color in the top bar / make it pale, etc. I think that's the route we'll end up going with the coloring.

No icons needed for changing that sort of thing. Although the S icon is looking a bit drab these days. unsure how to improve it, though.

**Comment by bshah2016** [comment]
I agree. I'll play around with some S designs. What are the different color S icons for anyways? You have red, yellow, ect with varying levels of bars.

**Comment by EladBezalel** [comment]
Yea well that's probably better :)
I'll think about S designs too

**Comment by MeoMix** [comment]
https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/background/model/chromeIconManager.js#L105

The icon is green when Streamus is playing, yellow when paused, red when muted. The number of bars represent the volume of Streamus in 25% increments.

**Comment by MeoMix** [comment]
I think that it would be a bit too jarring to change this continually. I'll keep the state just in the icon for now, but potentially improve the icon's ability to convey state.
