### ISSUE TITLE
Remember the title of deleted YouTube videos that are still in a Streamus playlist

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#362]
I do not know how Streamus works currently so maybe this issue is invalid.

When a YouTube video is deleted (from YouTube), YouTube does not remember the title of the video. In playlists on YouTube containing the deleted video, instead of the title of the old video it says something like "Deleted video". Sometimes that title is very useful because the user can search the title on the Internet and most probably find the old content in another place, maybe still on YouTube. So Streamus could improve on this: instead of saying "Deleted video" it could show the title of the deleted video.

**Comment by MeoMix** [comment]
Streamus does remember the title of the video. The only thing that goes missing is the image to show that it's been removed. It won't play, either.

I played around with automatically detecting and replacing songs which were removed on copyright grounds, but there's not always a match on YouTube and having your songs randomly change to not what you intended was really bad UX. 

Thanks for the feedback though!
