### ISSUE TITLE
Streamus flashing "Loading YouTube Try 1 of 10" repeatedly to very small % of users

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#367]
Not sure what's up with it just yet, but I've had this complaint 2-3 times in the past few days.

From a user:

I see spinner and message "loading youtube attempt 1 of 10" . This message appears and hides repeatedly. I could not collect any additional debug information from console. May be reason in my system. I use Chromium + Ubuntu 12.04 and Pepper flash plugin instead official from Adobe.

**Comment by richardsonvix** [comment]
Same problem yesterday.

Chrome 40.0.2214.111 m

**Comment by International** [comment]
Happens on my system as well. Ubuntu + Win7. Version 40.0.2214.111 (64-bit)

**Comment by marcguilera** [comment]
It's not loading for me neither. I use chrome 40.0.2214.111 (64-bit) on Mac OS 10.10.2

**Comment by MeoMix** [comment]
Guys, these are all complaints related to #417 

I fixed the code yesterday as you can see by the master branch commit. I pushed the changes to the Chrome Web Store. The changes were flagged as needing manual review by Google. I am now waiting for that to happen. I made announcements as such on Reddit, FB, and Twitter.

**Comment by richardsonvix** [comment]
Thanks.
