### ISSUE TITLE
Should the volume icon be larger?

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#372]
Icon sizing has always been a bit tricky since the square dimensions of an icon don't necessarily correlate to the "size" of the icon itself.

A user complained that they felt that the volume icon is too small. I've looked at it for too long to be able to tell. How do others feel?

**Comment by Dumbaz** [comment]
It is indeed quiet small, and there is lots of empty space.
![image](https://cloud.githubusercontent.com/assets/6582804/5894078/2857a360-a4fb-11e4-80e9-8b41ebf6806f.png)

Mabye add some more curves to make it look more like the svg below to fill space right of it?
![image](http://upload.wikimedia.org/wikipedia/commons/2/21/Speaker_Icon.svg)

**Comment by JordanBlakey** [comment]
With volume at 100% it's visually equivalent to your skipping track buttons, but not below that. I think if the speaker were big enough by itself to hit this balance it might look a little better.

It's also functionally distinct from the search bar, but is grouped with it... might throw it to the right of the play and skip buttons, as this is the convention in Spotify, iTunes, and Youtube. Doesn't bother me as is, but something to think about.

**Comment by MeoMix** [comment]
Alright, I think I'm going to bump it up to 24px. It feels sliiiightly too large to me, but I think that I'm just used to the smaller one and I'm not respecting the fact that it is a high-priority icon. People need to be able to find the volume control quickly which means having it slightly too small is worse than too big.

I think that moving to the far-right is nice in theory, but in practice really messes with the weighting/alignment. I tried it for a while.
