### ISSUE TITLE
UX questions regarding playlists

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#374]
Hey all,

Some concerns I've had regarding UX surrounding playlists. I'd like some feedback. 

- When creating a new playlist, should the playlist be created and marked active, or should it be left inactive? I'm hard-pressed to think of a time I do not want the playlist to be active, but I'm also hesitant on changing selections for the user without them having initiated it.

- Does the above answer change when considering that a playlist can be created either through the 'Create Playlist' dialog or through the 'Create Playlist' simple menu item? In the latter, the user can see all of the active playlist's songs and perhaps they were working with them. In the former, they're clearly not interacting with those songs.

- Should activating a playlist via click automatically close the navigation drawer? I assume doing it automatically (as described above) would not close the drawer (? maybe it would?), but I often find myself doing the same motions of creating a playlist, clicking it active, then closing the drawer. I feel like that could be simplified.

- Users sometimes feel like they can't rename a playlist. While possible, I think that they often double-click on a playlist name in the navigation drawer and expect it to be editable. I tried this in the past, but, from a UI standpoint it's pretty messy. You can't convey validation errors well in such a small space. So, I'm hesitant, but am also thinking about it. An alternative, or potential other addition, would be to allow the user to double-click on the Playlist Title in the main window and edit there.

**Comment by michael-jerred** [comment]
1. I agree that there is no reason not to select the playlist when it is added. Sometimes I copy multiple playlist URLs and create the playlists in streamus from them, which means I don't really want the playlist to open, but I also have no reason to keep the current one open either.
2. I think this doesn't change anything, if I'm working on ordering a playlist so intently that closing it would be annoying, I'm not likely to be creating new playlists.
3. This is better now that the drawer closes automatically.
4. The context menu 'Edit' could be 'Rename' instead as that is all it does.

**Comment by MeoMix** [comment]
Hey thanks for the feedback. I agree on 1/2 and will make that change, 3, as you know, is done. Playlists will have more properties in the future -- like when you import a Playlist from YouTube I will need to remember its YouTube URL and show it to you there. You might also be able to ban songs from showing up in radio mode, but link that to a playlist, so whenever you load the playlist those songs can't be random'ed into.
