### ISSUE TITLE
Change volume when rotating the mouse wheel over the Streamus icon

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#383]
This is a great feature of the volume icon in Ubuntu and I would love it if it were implemented in Streamus too. I don't know if it is possible but I hope it is.

**Comment by MeoMix** [comment]
Hey,

I don't believe this is possible. There's no real event handlers for user-driven events when the UI isn't open unless it's a keyboard shortcut. 

Sorrrry! Blame Chrome not Streamus. :p

**Comment by MeoMix** [comment]
https://developer.chrome.com/extensions/browserAction
