### ISSUE TITLE
Record language being used by users

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#384]
https://developer.chrome.com/extensions/i18n

The chrome i18n methods provide the ability to detect which language Streamus is being rendered in, or attempting to be rendered in.

There are two methods, I am unsure of their differences:

chrome.i18n.getAcceptLanguages
chrome.i18n.getUILanguage

It would be nice to keep track of these values by storing it either on the User object or on a new object which has a FK to the User object. This way I can tell which i18n files need the most attention.

If the client-side logic can be done by someone else then I'll happily add the necessary work to the server to persist the data.

**Comment by deemr** [comment]
Hi Sean, I wrote you a email on last Friday with Polish locale file. I would be glad if you could add it into extension or if you have any comments to it please write me back ;) 


Have you seen this? 
Gets the browser UI language of the browser. This is different from i18n.getAcceptLanguages which returns the preferred user languages.

**Comment by MeoMix** [comment]
Hey,

I know, I've got your e-mail. I'm just cleaning up my locale's file today and removing unused stuff / simplifying sentences. I'm also putting together a Google Docs to keep track of all the different translators.

And yeah, I did see it, I just don't understand what the difference is between preferred user language & language of the browser.

**Comment by deemr** [comment]
Ok, good :) there were some duplicated lines ^^

Well, I can't test it right now becouse I'm on my phone but maybe this getAccept get language from some browser settings and UI language is from OS? i will check it soon becouse I'm curious.

**Comment by MeoMix** [comment]
Language is now being recorded!
