### ISSUE TITLE
UX - Clicking the 'X' on Search closes the search window, but some people expect it to clear their search query

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#385]
I wonder what a good approach is to handling both of these scenarios? Currently there's no way to clear your typed text without ctrl+a + delete... admittedly, that's what I use, but should be doable from the UI itself, too.

**Comment by deemr** [comment]
Maybe pressing X would clear input box and clicking somewhere outside search area would actually close it?

**Comment by MeoMix** [comment]
Indeed, I've been considering that. The problem is there's a lot of buttons and stuff you'd like to click without closing the search results. Drag-and-drop, clicking 'Save' or 'Add' at the bottom, etc...

**Comment by deemr** [comment]
I know, maybe after pressing X check if search box is empty than:
if yes - close search window,
if no - clear input box.

**Comment by MeoMix** [comment]
Closing in favor of #524
