### ISSUE TITLE
New Icon Design

### ISSUE THREAD

**Issue by bshah2016** [MeoMix/StreamusChromeExtension#390]
Some icons that I created. If you like them, I can send over the zip.

![blue_19](https://cloud.githubusercontent.com/assets/10569647/5922520/3bb01f94-a61a-11e4-95c9-c6f16f0577f3.png)
![blue_38](https://cloud.githubusercontent.com/assets/10569647/5922519/3bad567e-a61a-11e4-91f1-23ad85286189.png)
![green_19](https://cloud.githubusercontent.com/assets/10569647/5922521/3bb05e78-a61a-11e4-9711-4593e07f178c.png)
![green_38](https://cloud.githubusercontent.com/assets/10569647/5922524/3bbc9da0-a61a-11e4-9647-0724c4462fc2.png)
![red_19](https://cloud.githubusercontent.com/assets/10569647/5922523/3bbbc51a-a61a-11e4-8233-94eaf7c68799.png)
![red_38](https://cloud.githubusercontent.com/assets/10569647/5922522/3bb8d01c-a61a-11e4-8d71-11db46f20be5.png)

**Comment by bshah2016** [comment]
![demo](https://cloud.githubusercontent.com/assets/10569647/5924036/32ef9cde-a626-11e4-8675-e3eb6eb0e342.png)

**Comment by MeoMix** [comment]
Appreciate it, but not going to change the icon at this point in time.
