### ISSUE TITLE
Add Key bindings for search and navigation

### ISSUE THREAD

**Issue by narendrans** [MeoMix/StreamusChromeExtension#399]
There is a short cut to bring the extension to front. What would be good is another shortcut mapped to search box. Once we start to type, using arrow keys should navigate the songs and highlight them and hitting enter should play the song. This would make it lot easier and faster to access the songs.

**Comment by MeoMix** [comment]
Navigating up/down is on my TODO list laready. See #70 

There's already a setting for 'Open to Search' which will cause it to be focused when opening. I'll keep in mind the possibility of a shortcut to open search via shortcut, though. :)
