### ISSUE TITLE
Support SoundCloud's API

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#4]
This is probably a huge undertaking, but a lot of users wish YouTube + SoundCloud were supported. Since other websites, like plug.dj, support SoundCloud -- I suspect it is quite possible.

I'm not sure if radio mode would work with SoundCloud -- a lot of the logic for smart picking related YouTube videos is given by YouTube's API. If SoundCloud doesn't have something similar... it won't be possible!

**Comment by sebastiansibelle** [comment]
Hey Sean, thanks for all the great work you've done on Streamus so far! 

Just wondering if you needed any help with this. I should have a little bit of time to spare in a couple weeks and would love to see this feature implemented! 

Cheers,

Sebastian.

**Comment by MeoMix** [comment]
Hey,

A couple of things:

- Help would definitely be appreciated. I played with SoundCloud's API for a bit and it was sort of a nightmare to use it for streaming playback in extensions. If you check out https://github.com/MeoMix/StreamusChromeExtension/blob/master/src/js/background/model/soundCloudAPI.js you can see I really tore things up. SoundCloud's API + an API they depend on, SoundManager2, both needed to be inlined into Streamus because of their dependencies on '//url' resolving to either 'http://' or 'https://'. This is not the case in extensions as they resolve to chrome-extension://.

- Furthermore, SoundManager2 has a tendency to want to provide a Flash player which is not really acceptable IMO. HTML5 <audio> or bust.

So, I hacked both of those out, got a song playing, and then realized that it's literally just <audio src='soundcloudurl' /> where the URL is easily derived from the track ID... a bit nicer than hacking at 8K LOC for the same effect.

So, I'm up in the air on that. Obviously need to use their API for everything other than streaming, but I'm thinking it would be easier to just do the streaming part internally?

The other thing on my mind, which I'll know soon, is how YouTube feels about SoundCloud. Streamus has finally caught their eye and I'm meeting with their BizDev/Partnerships teams over Skype next week. They might have opinions about coupling their API with SoundCloud, but I suspect they'll be OK with it. :) That said, they're the gate keeper, so gotta respect them.

**Comment by jimthedev** [comment]
@MeoMix How'd the discussions go. Would you still consider this?

**Comment by MeoMix** [comment]
Turns out this isn't possible. SoundCloud's TOS forbids using their API as an on-demand music service + forbids integrating it with YouTube.
