### ISSUE TITLE
UI reports not signed into chrome, when actually I am

### ISSUE THREAD

**Issue by boyvinall** [MeoMix/StreamusChromeExtension#403]
Every time I go into streamus from a fresh browser session, I'm told that I'm not signed into chrome (and so playlists cannot be sync'd) even though I am.  I've spoken to other users, seems they're not affected, so not sure why I am. 

![image](https://cloud.githubusercontent.com/assets/1652176/6023947/a9d19a16-abbf-11e4-977b-d07b548505c1.png)

I've tried disabling all other chrome extensions but that doesn't seem to have helped.  I'm on OSX 10.9.5 with chrome 42.0.2288.6 dev (64-bit)

If I get time, I will try to look into this, but thought it worth raising an issue now anyway.  Let me know if there's any info you need.  Thanks for the great extension :)

**Comment by MeoMix** [comment]
https://code.google.com/p/chromium/issues/detail?id=449066

It's this bug, I think? 

Or maybe Chrome Dev is doing it?

Long story short, chrome.identity.getProfileUserInfo is returning string.empty for your ID. It's a known issue on ChromeOS, but it should be fine on Mac.

**Comment by boyvinall** [comment]
Yep, I've gone to chrome stable and it seems to be ok now - seems that's an issue on Mac after all.  Thanks.

**Comment by MeoMix** [comment]
This is fixed in the new version, just FYI. You can go back to non-stable versions if you'd like.
