### ISSUE TITLE
Search process never ends when searching a URL of a video removed from YouTube due to copyright issues

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#406]
I clicked on the search button and pasted this string in the search box: `https://www.youtube.com/watch?v=WIvQ2B1ZZJc`. The search process started automatically but it never ends.

**Comment by MeoMix** [comment]
Thanks for the bug report! I think I (incidentally) have this fixed in
the dev branch already, but will double-check. :)

**Comment by MeoMix** [comment]
Alright, it is definitely fixed in dev, but it just says 'No results found'

I guess that's OK for now, but I'd love to convey better error messages at some point in the future.
