### ISSUE TITLE
No way to remove selected items from stream

### ISSUE THREAD

**Issue by michael-jerred** [MeoMix/StreamusChromeExtension#409]
There is the remove all button which clears the whole stream, and there are the individual buttons which remove a specific track, but no button to remove the currently selected tracks.

Also applies to playlists.

**Comment by MeoMix** [comment]
This is actually fixed in the development version. :) 
![image](https://cloud.githubusercontent.com/assets/1380995/6049403/e9076812-ac6b-11e4-9ad2-be38d376d7c0.png)
