### ISSUE TITLE
Malformed loading symbol in some environments

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#418]
This is the second time I've heard of a user saying that the loading icon is broken.

It looks like this: 
![image](https://cloud.githubusercontent.com/assets/1380995/6176301/89cf3454-b2b2-11e4-823d-fb93b46bd1ce.png)

The only way I was able to reproduce this issue is by setting the text rendering direction to right-to-left. However, this is not the case on their machines and forcing it to left-to-right did not resolve their issue.

What else could it be? The issue does not exist on Polymer's website, https://www.polymer-project.org/components/paper-elements/demo.html#paper-spinner

Last user reported it on Chrome 40.0.2214.111 on Linux

**Comment by zlsa** [comment]
The issue does not occur in the Polymer demo but does in Streamus.

**Comment by MeoMix** [comment]
Still unable to reproduce. Closing for now.
