### ISSUE TITLE
Sync playlist with youtube's copy

### ISSUE THREAD

**Issue by hypershadsy** [MeoMix/StreamusChromeExtension#429]
I know you create a Streamus playlist and have it copy all tracks from a YouTube playlist. Why not extend this functionality so users don't have to update both manually?

"Sync" is a two-way word. That is, it describes

* when the Streamus playlist is changed, the YouTube playlist copies
* when the YouTube playlist is changed, the Streamus playlist copies

I personally only need one of these bullet points, but both would be appreciated.

**Comment by MeoMix** [comment]
Closing, duplicate of #16
