### ISSUE TITLE
Reinstall Leaves Streamus Blank

### ISSUE THREAD

**Issue by zQueal** [MeoMix/StreamusChromeExtension#433]
I recently updated Chrome and was forced to reinstall Streamus. The extension will now not load at all.

![jgdpyw](https://cloud.githubusercontent.com/assets/239193/6223971/e0048d5a-b641-11e4-93ed-e71d809ea542.png)

**Comment by MeoMix** [comment]
If you go to chrome://extensions/, find Streamus, uncheck 'enabled' next to it, and then re-check 'enabled' does that fix it?

**Comment by zQueal** [comment]
I removed the extension which I grabbed from github and installed it via the link on the main website. Working fine now.

This ticket is technically solved by installing the extension via the website. But any ideas why I was unable to get it working by dropping the extension folder into the chrome extensions tab?

**Comment by MeoMix** [comment]
Could you give me exact steps to reproduce and I'll try to answer your
question?

Was this the master branch, or the dev branch? Were you following the steps
provided in the ReadMe to get up and started, or were you taking other
actions? You're on Chrome 40.0.2214.111?

**Comment by zQueal** [comment]
I'm running 39.0.2171.62 beta-m (64-bit). 

It looks like I pulled the development branch by accident, instead of master. Uninstalling the plugin and using the master branch works just fine.
