### ISSUE TITLE
Clicking the Streamus icon does not focus the window with the Streamus tab if the tab is in another window than the clicked icon

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#434]
This happens when the *Open in tab* option is enabled and you have two or more windows. If the Streamus tab is in *Window 1*, and the Streamus button is clicked in *Window 2*, the tab in *Window 1* becomes selected but the selected window is still *Window 2*.

**Comment by MeoMix** [comment]
heh.

I realized this bug when I was first writing the code, but I think it required elevated permissions or something to be able to detect active window. I'll double-check though, ty.

**Comment by MeoMix** [comment]
Okay, I decided it'd be best to just create a new tab in the current window rather than bringing the other window to focus. Could be bad UX (what if porn was hidden or something and I showed that window).
