### ISSUE TITLE
Keyboard Shortcuts lost after connecting Chrome Profile to Google (or extension update)

### ISSUE THREAD

**Issue by dlh3** [MeoMix/StreamusChromeExtension#436]
I noticed today that the Keyboard Shortcuts that I previously configured for Streamus had reset to default.  I'm not certain of the cause, but I believe it was one of:

1. Connected Chrome profile to Google account (which has never before been connected to a profile with the Streamus extension). *(most likely cause)*
2. Extension updated to newer version.

Not sure if this is a bug/feature deficiency in Streamus or in the Chrome extension framework, but it would be nice if the Keyboard Shortcut settings were merged into the Google Account-backed Chrome profile.

**Comment by dlh3** [comment]
May relate to #432; perhaps logging into Chrome blew away the localeStorage.

**Comment by MeoMix** [comment]
Hey there,

Extension keyboard shortcuts aren't able to be configured via JavaScript at all. I can't read the ones you have set nor can I set them for you outside of default suggestions in manifest.json.

Losing your keyboard shortcuts definitely sucks, but isn't something Streamus is actively handling. So, I don't think it's a bug on my end. It might be worth reporting to Google if it happens to you again, though. :)
