### ISSUE TITLE
Add Streamus to notification area on Windows 7 (or equivalent on other OS's)

### ISSUE THREAD

**Issue by camdecoster** [MeoMix/StreamusChromeExtension#439]
It would be nice to be able to bring up the Streamus UI without having to go into Chrome. I imagine it would present the UI when I click on the icon in the notification area.

**Comment by MeoMix** [comment]
The Desktop Notification area is built using a pre-defined template provided by Chrome, https://developer.chrome.com/apps/notifications#type-TemplateType

I don't have the ability to do much with it at this point in time. Maybe if/when Google releases a way to customize the notifications with HTML then I could add some functionality. We'll see :)

**Comment by camdecoster** [comment]
Okay. I assumed that it was possible since some other extensions do this, but I realize now that they're all made by Google. Hopefully they'll open it up one of these days.

**Comment by MeoMix** [comment]
Can you show me an example? More than happy to take a look. I suspect you're talking about their usage of Chrome Panels. If so, then yeah, Streamus would need to be whitelisted to take advantage of that functionality + I've been told it's being deprecated in favor of something else, but I don't know what yet.

**Comment by camdecoster** [comment]
Hangouts for example:
https://chrome.google.com/webstore/detail/hangouts/nckgahadagoaajjgafhacjanaoiihapd

**Comment by MeoMix** [comment]
Yep, hangouts uses Chrome Panel, I actually asked Google for this
functionality like a year ago and got denied, but, since meeting with
YouTube, there's talks of trying to get the Chromium team to change their
mind.

My request:
https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/oh-ztVT6Xok

On Mon, Feb 23, 2015 at 11:54 AM, Cameron DeCoster <notifications@github.com

**Comment by camdecoster** [comment]
Ah. Well, I guess I'll just be satisfied with your extension as is. Thanks for looking into it.
