### ISSUE TITLE
Hangs with "Loading youtube attempt 1 of 10"

### ISSUE THREAD

**Issue by amishurov** [MeoMix/StreamusChromeExtension#451]
Hello, I got message from title in the extension view.

Also I get repeatedly this error in background console

GET https://i1.ytimg.com/vi/J1Ol6M0d9sg/hqdefault.jpg 404 (Not Found) html5player.js:1618
3Untrusted origin: chrome-extension://boadgeojelhgndaghljhdicfkmllpafd www-embed-player.js:331
GET https://i1.ytimg.com/vi/J1Ol6M0d9sg/hqdefault.jpg 404 (Not Found) 

My env configuration:
Streamus 0.169
Chromium Version 37.0.2062.120 Ubuntu 12.04 (281580) (64-bit)
Google Cast extension is installed. I tried to uninstall it and than run streamus but it still is not working.

Thanks

**Comment by MeoMix** [comment]
Hey,

Does updating your Google Chrome version fix anything for you? You're
~3 versions out of date currently.

Sean

**Comment by amishurov** [comment]
Unfortunately, Precise (12.04) dist don't suggests versions of chromium newer than 37. I'll try to find new binary and tell about results. Please don't close this ticket yet.

**Comment by MeoMix** [comment]
Sure. I won't close it. Also, does normal YouTube work for you?

**Comment by amishurov** [comment]
YouTube works as expected

**Comment by amishurov** [comment]
After clear install chromium 37  problem disappeared. I really don't understand the  reason but now all works fine. Thank you

**Comment by MeoMix** [comment]
Glad to hear it! :)
