### ISSUE TITLE
add to streamus not working

### ISSUE THREAD

**Issue by renegaed** [MeoMix/StreamusChromeExtension#456]
First of all. I love the extension and I think you've done a fantastic job!
When I click the "Add to Streamus" button I'm getting "An error occurred".
It doesn't make a difference if I change playlists, still get the same issue.

Thanks.

**Comment by MeoMix** [comment]
Hey,

Are you still having this issue? This has been a problem in the past, but, as far as I am aware, it is working properly at this point in time. If so, what version of Streamus are you using, which browser, and which version of browser?

Thanks!

Sean

**Comment by renegaed** [comment]
ok now it has spontaneously started working. I have no idea why. Perhaps you fixed something?

**Comment by renegaed** [comment]
I am using Chrome: 40.0.2214.115 (64-bit) on my Max OSX with streamus version  0.171
