### ISSUE TITLE
Allow playlist to be refreshed to load new content

### ISSUE THREAD

**Issue by louim** [MeoMix/StreamusChromeExtension#460]
Hello!

I would like to have the ability to refresh an imported playlist. Let's say I have imported a youtube playlist, if the original playlist gets new items, the Streamus playlist won't get those. Ill need to recreate a new playlist each time I want to update it. I think there could be a button to allow a playlist to be refreshed, or it could be done automatically each time the playlist is added to the play queue. 

What do you think?

**Comment by MeoMix** [comment]
Duplicate: https://github.com/MeoMix/StreamusChromeExtension/issues/16

**Comment by louim** [comment]
Oops, I had a quick stroll trough the issues, guess I didn't go far back enough. :smile:

**Comment by MeoMix** [comment]
:) It's all good. It's quite common. I really need to work on that feature asap.
