### ISSUE TITLE
An error was encountered notification when adding any video to any playlist

### ISSUE THREAD

**Issue by b3t** [MeoMix/StreamusChromeExtension#466]
Exactly this issue - https://github.com/MeoMix/StreamusChromeExtension/issues/366

The error seems to be caused because the video was playing in a playlist and couldn't add the video to the streamus playlist correctly.  The workaround seems to be if I go to the individual youtube url and add to streamus, which would then work correctly.

**Comment by MeoMix** [comment]
Can you give me more information? Are you signed into YouTube? What browser/version? What version of Streamus? What song / for all songs?

**Comment by MeoMix** [comment]
I went ahead and changed the code to always load via URL rather than trying to scour the page for the video's ID. Should work better now. :+1:
