### ISSUE TITLE
The ui is messed up

### ISSUE THREAD

**Issue by The-Fred** [MeoMix/StreamusChromeExtension#477]
http://i.imgur.com/PBgvv5T.png

**Comment by louim** [comment]
I'm experiencing the same problem. 
Using Chrome Canary, haven't tested in Chrome stable.

**Comment by MeoMix** [comment]
Can someone confirm this is canary-only? Not super keen on trying to make patches that only target Canary as it could just be a bug in Chrome at that point, or perhaps a change to their CSS spec.

**Comment by subnomo** [comment]
I'm using Chrome dev branch (version 43.0.2357.18), I'm also getting this bug.

**Comment by MeoMix** [comment]
Alright, I'll check it out. Sounds like something has changed.

**Comment by mmacmillan** [comment]
@MeoMix It appears when the playlist contains enough items to cause vertical scroll in either pane, the "footer" disappears and neither pane can be scrolled.  I am using canary as well.  Tested in chrome 42.0.2311.90 and could not reproduce.

**Comment by MeoMix** [comment]
I've got this fixed locally. It'll be in the next update. Chrome changed how flexbox works.

**Comment by louim** [comment]
Thanks!! With all the controls hidden and unable to scroll, the extension was pretty hard to use ;)

**Comment by MeoMix** [comment]
For sure :) 

http://stackoverflow.com/questions/29907626/flexbox-max-height-interpretation-change-on-chrome 

Here's more details on the issue if you're curious.
