### ISSUE TITLE
Sign in failed

### ISSUE THREAD

**Issue by torzsmokus** [MeoMix/StreamusChromeExtension#481]
I would appreciate any comment on what can cause this message and where/how can I debug it.
I’m getting this after re-enabling the extension. It was disabled for a few weeks.

**Comment by MeoMix** [comment]
Can you please ensure that your PC is fully up-to-date? I think you're
using an insecure SSL certificate to try and communicate w/ my server.
Happens on PCs which aren't up to date

**Comment by torzsmokus** [comment]
I am using Ubuntu 14.04 LTS with daily updates.
When I tried to debug the problem by ‘inspecting’ the extension, first I found a pair of unwanted quotes around the userid in the request to the server, causing a 404. (The request worked normally without the quotes.)
Then I found that the chrome:extensions page said “This extension may have been corrupted”. After having clicked “Repair”, everything seems to be OK.

I have no idea what caused this intermittent issue but I consider it solved.
