### ISSUE TITLE
bug ? Streamus freezes and won't play any song

### ISSUE THREAD

**Issue by kublun** [MeoMix/StreamusChromeExtension#482]
Sometimes the extension simply won't play the selected song, I don't know if this was reported before.

My  streamus version is 0.172 and chrome version 41.0.2272.118

I usually have a lot of tabs loaded and only tweetdeck extension loaded.

**Comment by MeoMix** [comment]
Well, thanks for the info... I haven't heard any other reports of this and I haven't had it come up for me personally. I know that in Chrome v42 they fixed a memory leak issue in Google Chrome which would cause extensions to take up more and more memory the longer they ran. Maybe that was related to your issue.

**Comment by kublun** [comment]
This bugs still persists, I noticed that after clearing the Chrome cache it works again smoothly.
