### ISSUE TITLE
Clicking Streamus Button should close the dialog

### ISSUE THREAD

**Issue by dlh3** [MeoMix/StreamusChromeExtension#483]
When the Streamus dialog is open (after clicking the extension's button), the button is depressed.  Clicking the button again should close the dialog.  Instead, it closes but re-opens the dialog.

![image](https://cloud.githubusercontent.com/assets/648035/7193548/fc943608-e456-11e4-93dc-3ac0509cd024.png)

**Comment by MeoMix** [comment]
This is functionality built into Chrome, not Streamus. All extensions work this way. File a bug report with Google if you think it should change. :)
