### ISSUE TITLE
Indefinite reload and extension hang for a particular song

### ISSUE THREAD

**Issue by ghost** [MeoMix/StreamusChromeExtension#484]
Play https://www.youtube.com/watch?v=G9hAP106sSg through Streamus

Extension keeps reloading indefinitely.

**Comment by MeoMix** [comment]
Yeah, YouTube's API is throwing a weird error for some songs. I need to investigate it asap, just haven't had the time yet.

**Comment by MeoMix** [comment]
Closing in favor of #479
