### ISSUE TITLE
Evaluate usages of _.defer vs requestAnimationFrame

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#487]
I think I've used _.defer in spots where RAF would be more appropriate & would provide a (very slightly) snappier UX.

**Comment by DanPantry** [comment]
I can't see any uses of `_.defer` that aren't suited. *Perhaps* in the cases where you are adding, or removing, classes to the DOM, but honestly - that's not what RAF is for. I think your use of `_.defer` is fine.

**Comment by MeoMix** [comment]
Why do you feel like using RAF for adding/removing classes from the DOM is
not suited? I felt like that was a really optimal use case for it. Class
gets added before the browser has a chance to acknowledge the DOM element's
original state -- no CSS transition. Waiting a frame is the minimum amount
of time needed for that to occur.

**Comment by DanPantry** [comment]
I didn't notice they were animation classes. 5 hours ago = no coffee. My mistake.

**Comment by MeoMix** [comment]
Haha, no worries! Just was curious :)
