### ISSUE TITLE
Create a Firefox version of Streamus

### ISSUE THREAD

**Issue by silviubogan** [MeoMix/StreamusChromeExtension#489]
I am sure that many Firefox users will be happy to have a Firefox version of Streamus.

**Comment by MeoMix** [comment]
https://streamus.com/frequently-asked-questions/general-firefox

I already work on Streamus (for free!) ~60 hours/wk. I can't realistically see myself trying to support a browser I don't use. It doesn't provide any benefit to me. The code is open-source so if someone was feeling adventurous they could port it to FF, but I've got a long list of goals for this software and, at least for right now, FF isn't on the short list.

Sorry! <3
