### ISSUE TITLE
Search for videos without clicking on the magnifying glass icon

### ISSUE THREAD

**Issue by guitarrist** [MeoMix/StreamusChromeExtension#492]
I do not know if you think it would be a good idea, but it would be amazing if it was possible search for a video without necessarily clicking in the magnifying glass icon, as well as in the Windows 8 start menu. 
So it would not be necessary to remove your hands off the keyboard to use the Streamus by simply type the shortcut configured to activate the extension and then enter the search.

Following the same idea, it would be interesting to browse through the video results using the up/down arrows.

**Comment by MeoMix** [comment]
Hey,

If you go into settings you can enable the setting 'Open to Search' which will cause Streamus' search menu to open up automatically w/ the input focused whenever Streamus opens. This means that if you bind a shortcut to open Streamus it'll do just as you say.

The other issue is already being tracked here: https://github.com/MeoMix/StreamusChromeExtension/issues/70 :) 

Closing for now. If you have more to add feel free to re-open! Thanks!
