### ISSUE TITLE
Site not loading over HTTPS

### ISSUE THREAD

**Issue by Matt1360** [MeoMix/StreamusChromeExtension#499]
Howdy,

In Gentoo (Linux), on Chrome 40 (detailed below), I found the streamus.com site not loading over HTTPS, with the errors as shown below (namely, the CDN for the scripts not being over HTTPS as well).

Things like this remind me I'm using HTTPS Everywhere, hehe.

````
-[~:$]- chromium --version
Chromium 40.0.2214.111
````

![im an image!](https://reenigne.net/screenshots/1430498298.png)

**Comment by MeoMix** [comment]
Hey,

Uhhh... clkmon.com is adware! I think your computer is infected and
Streamus is preventing itself from loading because it doesn't want to
expose sensitive data. There's no reference to clkmon in my source code.

Thoughts?

**Comment by Matt1360** [comment]
Whoop, that was coming from another extension (that's apparently being quite greedy).

I am still hitting that second error though, [as seen here](https://reenigne.net/screenshots/1430501715.png), which is leaving me with a blank page.

Expanding the error shows some Backbone traces.  Have you experienced this before?

**Comment by MeoMix** [comment]
Oooh, I know that one, actually. Huh. Okay, I'll put some defensive checks in there.

chrome.runtime is not defined... which it should be on all webkit browsers. Using chrome.runtime from a website is how I allow for adding playlists from the website and detecting that Streamus is installed. It's weird that your browser doesn't support it but does identify as WebKit... might be worth filing a bug. Can I get some more details on your exact OS and Browser versions (down to minor vers) and I'll check for any bug reports on Google's side.

**Comment by Matt1360** [comment]
Ah, I see what you mean.

![i am another image!](https://reenigne.net/screenshots/1430502282.png)

And [here](http://pastie.org/pastes/10123958/text?key=3kogurlsnzr0dbswfiouiw)'s a pastie of some `eix` and `uname` output for this box.  I'm about to head out to lunch, so I'll actually update chromium, which will take some time to compile :).

My desktop at home, where I threw streamus onto this morning is running `41.0.2272.76` which worked like a charm.  I'll be running `42.0.2311.90` in about an hour... probably.

**Comment by Matt1360** [comment]
After finally closing everything out for the day, and trying in the new version of Chromium, I can safely say the site is working as intended, and that `chrome.runtime` exists in this version.

I'll leave it to you to close when you're ready.  Thanks!

**Comment by MeoMix** [comment]
Good to know, thanks for the insight.
