### ISSUE TITLE
Allow context menu from other sites

### ISSUE THREAD

**Issue by jimthedev** [MeoMix/StreamusChromeExtension#508]
If I recall, Chrome's security makes you be explicit about what sites context menus will show up. With that said, it be great to be able to select some text on a random radio site and be able to select "Play with Streamus". Even better would be the ability to add it to a specific playlist right from the context menu.

Great work.

**Comment by MeoMix** [comment]
You can already do that... :p Ratatat - Loud Pipes 
![image](https://cloud.githubusercontent.com/assets/1380995/7480653/ea87bd64-f31e-11e4-966d-bb60af898b4d.png)

**Comment by MeoMix** [comment]
And to clarify -- No, you just request contextMenu permission and then specify your criteria. It doesn't require additional perms on a per website basis for context menus -- only for HTML injection.
