### ISSUE TITLE
Usability copying song name currently playing

### ISSUE THREAD

**Issue by newtonianb** [MeoMix/StreamusChromeExtension#509]
When I'm in radio mode a couple times I get some songs I want to copy the name but I can't copy it from the top right where it's actually playing. 

I have to actually find it in my list, right click and copy it from there, it's a bit counter intuitive. 
It's a bummer too because all I really want is to copy the name of the song and I can't even select the name from the top right area.

This gets me .... every time

![s1](https://cloud.githubusercontent.com/assets/2313644/7504586/7deafe22-f419-11e4-8991-50569ba4217f.jpg)
![s2](https://cloud.githubusercontent.com/assets/2313644/7504585/7dea6386-f419-11e4-9bbc-b9477bd5b429.jpg)

**Comment by MeoMix** [comment]
Okay, it's fixed. Will be in the next release by end of day.

**Comment by newtonianb** [comment]
:+1: :+1: 

thanks!
