### ISSUE TITLE
Notifications don't display if Streamus is open in a tab

### ISSUE THREAD

**Issue by jcme** [MeoMix/StreamusChromeExtension#518]
Currently the Chrome desktop notifications won't appear if Streamus is open in a tab, even if that tab doesn't have focus. In my opinion the notifications should only be suppressed if the Streamus tab is currently active - otherwise the information is still very useful for the user!

**Comment by MeoMix** [comment]
You're right. This will need to use the chrome.windows API to check and see if the window is active and also the tabs API to check if the tab is highlighted in the active window.

https://developer.chrome.com/extensions/windows

One concern is that we'll have to ping these APIs every time a notification is shown, but I don't think that it's very costly to do so. The other option is to try and keep track of which window is active and tab is highlighted, but I don't think there's a very good way to do that. So, checking every time is probably the right call.

The simpler option is to just suck it up and always show notifications even if the tab is highlighted and the window is active. Maybe that's better, but it'd be different than how Streamus works in the popup.

**Comment by MeoMix** [comment]
This seems to be working now? I ran it through a series of tests. Maybe I fixed it without remembering, but it looks good!
