### ISSUE TITLE
Playlist not switching to the next song

### ISSUE THREAD

**Issue by Orad** [MeoMix/StreamusChromeExtension#533]
I'm using chromium on Linux
I think that after the last update streamus stopped playing the next song and I must manually click the next track in order to continue the playback after the song is over.
Another issue that I encounter is that the time and the progress bar in the playback is not updating during the playback.
Everything else, including the audio, is working great.

**Comment by MeoMix** [comment]
Does reloading Streamus fix this issue? It sounds like YouTube's Flash player managed to get loaded somehow. There's a very small subset of songs which started causing Flash fallback about a month or two ago and I'm not sure when YouTube is going to fix that.

**Comment by Orad** [comment]
No reloading, or even closing all chrome processes, doesn't help, however I've found that it has to do with sound setup on this machine since on another machine with exactly the same chromium(and plugins) and OS it doesn't happen and this machine has some sort of virtual sound device so it may be related to that.
All other sound application are working fine. even streamus plays well just won't continue to the next track.
How can I help you debug it? I can't find any error message in the console.

**Comment by MeoMix** [comment]
I still think the hunch is that the Flash player is loaded.

If you go to chrome-extensions://, click 'developer mode', click 'background.html', look at the HTML mark-up generated, find the iframe for the YouTube player and dig inside of it there will be either a <video> element or a swf player. Can you confirm which there is?

Also, if you go to any YouTube song that you're trying to play, but view it actually on YouTube. Is it using Flash or HTML5?
