### ISSUE TITLE
Quick ADD TO when playing in browser from Youtube

### ISSUE THREAD

**Issue by ivansabik** [MeoMix/StreamusChromeExtension#568]
Would be great if there is something already opened in chrome Youtube (as a normal webpage), you could add it without needing to copy/paste the url.. like a "quick add to" of the video playing

**Comment by MeoMix** [comment]
![image](https://cloud.githubusercontent.com/assets/1380995/7755736/56f0b44a-ffab-11e4-8f09-b57af68dce18.png)


It exists in two forms already?

**Comment by ivansabik** [comment]
That was it -_-
