### ISSUE TITLE
How to start playing streamus using terminal in ubuntu (chromium)

### ISSUE THREAD

**Issue by potholiday** [MeoMix/StreamusChromeExtension#570]
Is there any way which we can open and play streamus extension from terminal in ubuntu. It would be easier for linux users if there is a command available to do the above task.

**Comment by MeoMix** [comment]
I have absolutely no idea, lol. I don't use Linux. I'm sure there are third-party programs out there which would let you map shortcuts to open Chrome and open the UI, but it is not possible to open the UI without a Chrome window open.

**Comment by potholiday** [comment]
meomix thanks for the reply..i have found a way to open your extension (as a new tab) from terminal but the problem is i don't know how to autoplay streamus. Do you have any function which can autoplay streamus? what i meant was when we open streamus extension it should loads the playlist and start playing songs (from the last played) with out clicking the play button.

**Comment by MeoMix** [comment]
Well, you can send a keyboard shortcut to Streamus to begin playback? Is that feasible?

**Comment by potholiday** [comment]
I was trying to automate streamus playing by a bash script. Basically when some one execute the bash script it will open the streamus as a new tab (which i solved) and should start  playing songs with out any external input. So No, keyboard shortcut will not work for my case but is their any kind of keyboard short cuts available. I am using this link "chrome-extension://jbnkffmindojffecdhbbmekbmkkfpmjd/foreground.html"  to open streamus. Is there any way i can pass "playing parameters" like available in web apps eg: google.com/?search=search+term

**Comment by MeoMix** [comment]
I don't have much desire to support passing query parameters into Streamus, sorry.

You can use a tool such as http://dev.man-online.org/man1/xdotool/ to simulate keyboard input which Chrome will happily respond to.

**Comment by potholiday** [comment]
K thanks for the prompt reply meomix and i will try that method

**Comment by MeoMix** [comment]
Lemme know how you get on with it. It'd be cool to have as instructions for others if you're successful.

**Comment by potholiday** [comment]
i will try and if successful i will let you know here itself

**Comment by potholiday** [comment]
Meomix i have asked this question in askUbuntu and this is the answer http://askubuntu.com/a/628997/414116

**Comment by MeoMix** [comment]
Did you try setting the keyboard shortcut to 'Global' instead of 'Chrome'?
Chrome can respond to shortcuts even w/o the window focused.

**Comment by potholiday** [comment]
I tried with 'global' but there was no response in streamus I kept Alt+Z as play command but it was not working. Then i changed it to `in chrome` and it was working
