### ISSUE TITLE
Proposal: Merge forces w/Soundcloudify

### ISSUE THREAD

**Issue by jimthedev** [MeoMix/StreamusChromeExtension#573]
Hi there, amazing work. Really enjoying the extension. It seems that there is another extension with the exact same goal. Would it make sense to work together to speed up development. I know the underlying technologies used are different, but figured it couldn't hurt to at least discuss the possibility of a merge to increase development speed on one or both of the projects through a shared library.

See the corresponding thread here: https://github.com/ptgamr/soundcloudify/issues/18

**Comment by MeoMix** [comment]
I spoke with him about it. I think we both have a strong desire to continue using the frameworks we've chosen to develop our software with. He has no interest in learning Backbone/Marionette and I have no interest in learning Angular. RIP.

**Comment by jimthedev** [comment]
Thanks for checking into it. Figured it was worth a shot.

**Comment by MeoMix** [comment]
Definitely. If anything, having someone else in this space has triggered my competitive side. :)

**Comment by jimthedev** [comment]
:+1: Good! The more competition the merrier.

**Comment by ptgamr** [comment]
Yeah, we are competitors, but we shared the same enemy: YouTube. lol !

**Comment by jimthedev** [comment]
Ha!

**Comment by ptgamr** [comment]
But surely I'll give Backbone a try :D
