### ISSUE TITLE
Mediakeys on Ubuntu

### ISSUE THREAD

**Issue by Immac** [MeoMix/StreamusChromeExtension#574]
Mediakeys on Ubuntu 14.04 don't trigger on global and take about 2 seconds to register when chrome is focused, other keyboard shortcuts work fine in both global and focused mode. I do not know why this might be. It works fine on Windows.

**Comment by MeoMix** [comment]
https://code.google.com/p/chromium/issues/list I'd report it here. I don't control how keyboard shortcuts are interpreted.
