### ISSUE TITLE
Handle "Song Cannot Be Played" Gracefully

### ISSUE THREAD

**Issue by dlh3** [MeoMix/StreamusChromeExtension#575]
When songs are in the playlist, but can't be played when they are reached, the player stops.  If this happens with the Streamus panel open, the "Song Cannot Be Played" dialog is presented, but when the panel is closed, there is no indication that this has happened.

It would be nice if the error were handled gracefully, and playback continued on with the next item in the playlist.  Perhaps the item could be marked as unplayable.

**Comment by MeoMix** [comment]
Closing, duplicate:

- https://github.com/MeoMix/StreamusChromeExtension/issues/550
- https://github.com/MeoMix/StreamusChromeExtension/issues/380
