### ISSUE TITLE
Add to playlist popup (from save button on play queue) does not show all playlists

### ISSUE THREAD

**Issue by urscion** [MeoMix/StreamusChromeExtension#578]
When I click on the save button from a song in my play queue I can't see all of my playlists. I cannot scroll through all of them either. sometimes it doesn't even show the scroll bar.

As you move down the play queue, more and more of the popup box can be seen.

**Comment by MeoMix** [comment]
Can I see a picture? What zoom level are you using on your PC? PC stats?

**Comment by urscion** [comment]
sure
![streamus_cutoff_zoom](https://cloud.githubusercontent.com/assets/8176416/8018070/681c9bec-0bd8-11e5-9f09-264bd02d03e1.png)
![streamus_fulllist](https://cloud.githubusercontent.com/assets/8176416/8018071/681cba78-0bd8-11e5-8e82-6307e60beb51.png)
![streamus_cutoff](https://cloud.githubusercontent.com/assets/8176416/8018072/681e02a2-0bd8-11e5-8303-ff638d4fd944.png)

**Comment by urscion** [comment]
CPU-Z TXT Report
-------------------------------------------------------------------------

Binaries
-------------------------------------------------------------------------

CPU-Z version			1.72.1.x64

Processors
-------------------------------------------------------------------------

Number of processors		1
Number of threads		4

APICs
-------------------------------------------------------------------------

Processor 0	
	-- Core 0	
		-- Thread 0	0
	-- Core 1	
		-- Thread 0	2
	-- Core 2	
		-- Thread 0	4
	-- Core 3	
		-- Thread 0	6

Timers
-------------------------------------------------------------------------

	ACPI timer		3.580 MHz
	HPET timer		14.318 MHz
	Perf timer		3.330 MHz
	Sys timer		1.000 KHz


Processors Information
-------------------------------------------------------------------------

Processor 1			ID = 0
	Number of cores		4 (max 8)
	Number of threads	4 (max 16)
	Name			Intel Core i5 3570K
	Codename		Ivy Bridge
	Specification		Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
	Package (platform ID)	Socket 1155 LGA (0x1)
	CPUID			6.A.9
	Extended CPUID		6.3A
	Core Stepping		E1/L1
	Technology		22 nm
	TDP Limit		77.0 Watts
	Tjmax			105.0 °C
	Core Speed		1604.2 MHz
	Multiplier x Bus Speed	16.0 x 100.3 MHz
	Stock frequency		3400 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES, AVX
	L1 Data cache		4 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	4 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		4 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		6 MBytes, 12-way set associative, 64-byte line size
	FID/VID Control		yes


	Turbo Mode		supported, enabled
	Max non-turbo ratio	34x
	Max turbo ratio		38x
	Max efficiency ratio	16x
	Min Power		60 Watts
	O/C bins		unlimited
	Ratio 1 core		38x
	Ratio 2 cores		38x
	Ratio 3 cores		37x
	Ratio 4 cores		36x
	TSC			3410.0 MHz
	MPERF			3410.1 MHz

	Temperature 0		38°C (100°F) [0x43] (Core #0)
	Temperature 1		39°C (102°F) [0x42] (Package)
	Power 0			25.06 W (Package)
	Power 1			5.49 W (IA Cores)
	Power 2			n.a. (GT)
	Power 3			19.57 W (Uncore)
	Voltage 0		1.01 Volts (VID)

**Comment by urscion** [comment]
Let me know if you need anything else

**Comment by urscion** [comment]
Using Version 43.0.2357.81 m of Chrome

**Comment by MeoMix** [comment]
Hey,

Yeah you're right. Weird. Okay, I can reproduce this on my end and I'll have it fixed in the next patch. Thanks!

**Comment by urscion** [comment]
Excellent. Thanks!
