### ISSUE TITLE
Show next song in radio mode

### ISSUE THREAD

**Issue by HelpingHand1** [MeoMix/StreamusChromeExtension#580]
Just an improvement suggestion:

In radio mode, display the next song that is queued to be played next. Also, give the user an option to skip to the next song suggestion if he chooses.

Thanks for your awesome extension! It's become the only tool I play music with since GS went down.

**Comment by MeoMix** [comment]
Duplicate #1

**Comment by HelpingHand1** [comment]
Sorry, just saw the other post. Thanks anyway!
