### ISSUE TITLE
Sync playlists across Google account Chrome Extensions

### ISSUE THREAD

**Issue by xssh** [MeoMix/StreamusChromeExtension#583]
I need to add my playlists on each Chrome instance I'm logged on to. Ideally, I should have my extension's settings saved and synced.

**Comment by MeoMix** [comment]
They do. You just need to reload Streamus when moving between PCs - I haven't had the time to finish coding automatic refreshing. I thought there was an open issue for this but I don't see one, I'll embellish on a new issue in a while.
