### ISSUE TITLE
Streamus won't log me in

### ISSUE THREAD

**Issue by wizonesolutions** [MeoMix/StreamusChromeExtension#587]
It just keeps spinning. Screenshot: https://www.evernote.com/l/AAJFomQzcchBQaaqX9UUW3kG4AhI_h4SzOU

**Comment by MeoMix** [comment]
Hey,

Is this still an issue for you? Is your PC up-to-date with security patches? This is most commonly an SSL issues.

**Comment by wizonesolutions** [comment]
Seems good now, thanks.

**Comment by MeoMix** [comment]
Okie. I'll keep an eye on it. Server might've just had some planned downtime on AWS' side or something, unsure. I don't have fail-over servers b/c of $$
