### ISSUE TITLE
Streamus lose playing "state"

### ISSUE THREAD

**Issue by louim** [MeoMix/StreamusChromeExtension#588]
Hello!

Ill try my best to describe the issue: When playing a playlist, Streamus sometime think the music is paused even when it's playing. If I open the interface, the play / pause button is showing the "play" icon, meaning that the music should be paused. But the music is playing (and the time bar continue to progress). Keyboard controls have no effect, I am unable to stop the music. The only fix I found is clicking the time bar, which seems to update the playing controls or chose another song via the interface (prev / next on keyboard do not work in this case). 

It happens a lot (couple time in an hour). It also seems to prevent the correct function loop button. What I mean by that is the song will often stop at the end, instead of restarting. If I hit play on the keyboard (or the interface), it will resume.

I'm using Chrome Canary latest. Anything I can do to help debug or provide more info? It started to happen a couple weeks ago, was working totally fine before that :cry:

**Comment by MeoMix** [comment]
I haven't seen this happen + supporting Chrome Canary is kinda crazy. of course there will be bugs in the canary version of Chrome. If you're able to reliably reproduce on the stable channel then I'll take a look.
