### ISSUE TITLE
i cant find actual stream

### ISSUE THREAD

**Issue by Bound3R** [MeoMix/StreamusChromeExtension#595]
When adding a song to one of my lists, indicates that to me added to the current stream, the problem is that I can not see the temporal playlist,
in the previous version it had two tabs, one was playlist and the other the stream.

![Image of Yaktocat](https://streamus.com/img/emptyPlaylist.png)

**Comment by Magentah** [comment]
The currently playing stream is in the playlist dropdown in the top bar. It's the top item, called Stream.

**Comment by MeoMix** [comment]
As stated, it's all been combined into one, but apparently it's confusing.
Going to look into the possibility of having both ways.

**Comment by OSjerick** [comment]
I encountered this very awful. Sorry! I cannot find the way to play songs into the stream just by clicking.
