### ISSUE TITLE
Streamus trying to insert addButtonWrapper on every page

### ISSUE THREAD

**Issue by Derpp** [MeoMix/StreamusChromeExtension#596]
Is this normal behavior ? Happening on all YouTube pages, not just video pages.
![screen shot 2015-07-02 at 3 23 49 pm](https://butt.githubusercontent.com/assets/6655696/8485791/5e174ede-20ce-11e5-8fd6-171e1d665726.png)

**Comment by MeoMix** [comment]
I'll take a look. No, not normal behavior. ty for bug report.

**Comment by MeoMix** [comment]
Fixed it by adding a small check to the URL.
