### ISSUE TITLE
Streamus is now... broken! Song unable to be played (error, everytime I try to play something)

### ISSUE THREAD

**Issue by muffinjello** [MeoMix/StreamusChromeExtension#597]
Hello,
As the title says... Streamus has broken down on me since the new update. *Sigh*, makes me want to cry. 

Especially my discovery that the videos are loaded in the background, will I ever find a low-bandwidth and CPU method to listening to music on youtube? :sob: 
![Broken](http://s4.postimg.org/c0yxrggd9/Capture.png)

**Comment by MeoMix** [comment]
Hey,

As I've said in every other bug report, in the patch notes, on the website, on reddit, facebook, and twitter:

- Streamus is being blocked by UMG currently. All songs licensed by UMG are unable to be played in Streamus. I've reached out to them, but have no means of fixing this myself without breaking YouTube's Terms of Service and being taken down from the Chrome Web Store. Tweet @UMG and show your support for Streamus if you'd like to help.

- No, there is no way of loading only the audio of YouTube without breaking their Terms of Service. I've made it clear in my FAQ that Streamus does not provide any major bandwidth benefits for months and months now: https://streamus.com/frequently-asked-questions/general-bandwidth

**Comment by muffinjello** [comment]
Haha, oh wow.
@UMG really lives up to it's name with "universal" licenses. Universal over songs they clearly don't have any licenses or rights to. 

This is the most absurd thing I've ever heard.

**Comment by MeoMix** [comment]
*shrugs* YouTube things they have the license. I have no idea if they do or not, but that's all managed by YouTube and if I try to play the song it says "This content is owned by UMG"

**Comment by KoenRijpstra** [comment]
Can you change the notification to something more meaningful for the user? This notification gives the impression that there is something wrong with Streamus.

**Comment by MeoMix** [comment]
Feel free to submit a PR... I just worked 30 hours over the weekend after staying up 2 days straight to get the release out. Only so much time.
