### ISSUE TITLE
Separating "Stream" button from playlist menu

### ISSUE THREAD

**Issue by Wagk** [MeoMix/StreamusChromeExtension#598]
Previously, Streamus has split the screen into two, one for the playlist/search, one for the ongoing stream that is being played.

After the patch, the screens have been merged, and to select the ongoing stream, one must select it from the same menu as the saved playlists.

I would like to suggest moving the stream button to its own spot next to the playlists button.

This is so that people would be be able to mix songs from multiple playlists without the necessity of scrolling up and selecting the streams button, repeatedly.

**Comment by idmontie** [comment]
:+1: The new layout is completely intuitive compared to the split layout that was there before. Also, I didn't even realize that the dropdown and the hamburger menu were different (with the dropdown containing a "Stream" option).

I'm fine with it showing the Youtube video, but the layout change is killing me.

**Comment by MeoMix** [comment]
Yeah. I'm working on bringing back the split panel today. Sorry. There *were* reasons for doing it, but YouTube shot down those reasons and then gave me a deadline which didn't let me react much.

**Comment by MeoMix** [comment]
This is fixed in the development version. Going out later tonight.

**Comment by easternwawoman** [comment]
I'm too late for this discussion, I bet, but another thought is to use the
front-end developers' mega-menu concept?

**Comment by idmontie** [comment]
@MeoMix The split panel is back! :clap: Awesome job!
