### ISSUE TITLE
Black Video when Youtube buffers, or when connection to Youtube lost.

### ISSUE THREAD

**Issue by belackriv** [MeoMix/StreamusChromeExtension#600]
I was able to reproduce the black video I saw before.  If your connection to youtube is lost, the music will resume, but the video will be black.  Has happened when youtube buffered for me, and when my computer hibernated, but I had paused a song, then restarted it.

**Comment by MeoMix** [comment]
Word. Thanks! I will take a look at these. It sounds reasonable.

**Comment by MeoMix** [comment]
Closing this as I'm not using that means for showing video anymore.
