### ISSUE TITLE
Increase width of scrollbars

### ISSUE THREAD

**Issue by MeoMix** [MeoMix/StreamusChromeExtension#602]
Since they're only visible on hover I think it's OK to make them a bit wider for easier interaction.

**Comment by turuto** [comment]
Hi. Personally, and I don't know if you can take me as a example, even though I scroll a lot, I don't use the scrollbars that much, as I scroll using the mousewheel if a have a mouse, or the gestures if I'm on a touchpad.
So I'm not so sure whether it's worthy to invert time in such a feature

**Comment by MeoMix** [comment]
I think it'd probably just be a couple of extra pixels. Someone sent me an e-mail saying they were really struggling with dragging using the scrollbar. _shrug_
