### ISSUE TITLE
Streams don't skip unplayable songs

### ISSUE THREAD

**Issue by DrTall** [MeoMix/StreamusChromeExtension#603]
Hello,

I understand that Streamus refuses to play certain videos now due to YouTube's demands. When I try to play such a song, I get a pop-up error message "Song unable to be played" which is fine.

However, when such a song is queued in a stream, I think it would be better for Streamus to skip it and begin playing the next non-restricted song in the queue. The current behavior appears to be that Streamus stops playing entirely.

Thanks,
Sean

**Comment by DrTall** [comment]
Wow, grammar, how does.

**Comment by MeoMix** [comment]
Duplicate #380

**Comment by DrTall** [comment]
Doh, sorry. Thanks!
