### ISSUE TITLE
won't scroll with last update.

### ISSUE THREAD

**Issue by nomailme** [MeoMix/StreamusChromeExtension#605]
Just few minutes ago updated to the last version. Unable to scroll anymore in streamus popup window

**Comment by MeoMix** [comment]
Uhhhh? I can scroll fine.. any errors on the page when you inspect foreground.html?

**Comment by nomailme** [comment]
Just one which i don't think is relevant.

```
GET https://img.youtube.com/vi/gGsvOtT-_-I/mqdefault.jpg 404 (OK)curCSS @ main.js:12383jQuery.extend.css @ main.js:12848jQuery.each.jQuery.cssHooks.(anonymous function).set @ main.js:12887jQuery.extend.style @ main.js:12816(anonymous function) @ main.js:15961jQuery.access @ main.js:10326jQuery.each.jQuery.each.jQuery.fn.(anonymous function) @ main.js:15933Marionette.Behavior.extend._setHeight @ main.js:26612Marionette.Behavior.extend._setHeightTranslateY @ main.js:26580Marionette.Behavior.extend._setViewportHeight @ main.js:26477Marionette.Behavior.extend.onAttach @ main.js:26431(anonymous function) @ main.js:18327Marionette.View.Backbone.View.extend._triggerEventOnBehaviors @ main.js:19565Marionette.View.Backbone.View.extend.triggerMethod @ main.js:19554Marionette.triggerMethodOn @ main.js:18363(anonymous function) @ main.js:18838(anonymous function) @ js/background/main.js:936forEach @ js/background/main.js:3332Marionette.Region.Marionette.Object.extend._triggerAttach @ main.js:18837Marionette.Region.Marionette.Object.extend.show @ main.js:18816Marionette.Region.extend._showActivePanesView @ main.js:28586Marionette.Region.extend._onForegroundAreaRendered @ main.js:28582triggerEvents @ main.js:16238Backbone.Events.trigger @ main.js:16180Marionette.LayoutView.extend.onRender @ main.js:34438(anonymous function) @ main.js:18327Marionette.View.Backbone.View.extend.triggerMethod @ main.js:19552Marionette.ItemView.Marionette.View.extend.render @ main.js:19706Marionette.LayoutView.Marionette.ItemView.extend.render @ main.js:20667bound @ js/background/main.js:764Marionette.Application.extend._showForegroundArea @ main.js:34597Marionette.Application.extend._onStart @ main.js:34588triggerEvents @ main.js:16239Backbone.Events.trigger @ main.js:16180(anonymous function) @ main.js:18333Marionette.triggerMethod @ main.js:18351Marionette.Application.Marionette.Object.extend.start @ main.js:21150(anonymous function) @ main.js:34623context.execCb @ require.js:1665Module.check @ require.js:874Module.enable @ require.js:1158Module.init @ require.js:782(anonymous function) @ require.js:1431
```

**Comment by nomailme** [comment]
ok. One thing that I have noticed that //*[@id="foregroundArea"]/div[7]/div[1]/div has height of 1600px. Which is weird

**Comment by MeoMix** [comment]
Error is definitely relevant. Can I see a screenshot of it so I can try to better read it? Not entirely sure what's up with it.

Also, does reloading Streamus fix the issue? Settings -> Reload? Might just be a weird memory leak error surrounding updating.

**Comment by micspam** [comment]
http://gyazo.com/3df09da1f5521439917ae31005b1da48

This is the error I get after today's update.

Same issue as OP.

**Comment by andycjw** [comment]
I can't scroll after the last update either, and the bottom panel for 'clear, save stream' is also gone

**Comment by MeoMix** [comment]
Can you go to chrome://extensions, check 'developer mode', click 'background.html' underneath Streamus and tell me what errors appear on that page? I don't need to know about any cast_sender errors, but there's something else on that background page that's erroring out for you guys.

**Comment by MeoMix** [comment]
Aaaanyone? It's 2AM and I have to be up at 7:30 AM. If this needs to be patched I need to know in the next few minutes. My client error logging isn't showing anything related to this issue. @micspam  @andycjw @nomailme ?

**Comment by MeoMix** [comment]
Okay. Laying back down. I work until 5-6 tomorrow so won't be able to get a release out until tomorrow night if it's needed. Night.

**Comment by MeoMix** [comment]
Just kidding. Fixed it. Now it's 3AM and I really gotta try to get a few hours of sleep. v0.179 going live.

**Comment by andycjw** [comment]
you're the man, making this happen
