### ISSUE TITLE
Certain videos are not supported/don't play on streamus.

### ISSUE THREAD

**Issue by Lazybeer** [MeoMix/StreamusChromeExtension#607]
I can't get this music to work on streamus:

Road To Perdition (Score) - Splice https://www.youtube.com/watch?v=aM0Iu7Mdw4A

Lamb - Angelica https://www.youtube.com/watch?v=X0qwQqwKLlM

Wanted to report it as the playlist now jams whenever it tries to play it.

In case country restrictions has anything to do with it, I am from Norway and both links work for me on youtube, but the streamus app can't play them.

**Comment by dwminer** [comment]
I believe this is related to the change in [v0.177.](https://github.com/MeoMix/StreamusChromeExtension/releases/tag/v0.177) UMG has blacklisted any music licensed under them from playing on Streamus. Unfortunately I doubt this is something MeoMix will be unable to solve for legal reasons.

**Comment by nglinh** [comment]
For testing purpose, I assume we can use a different API key in order to load the videos?

**Comment by MeoMix** [comment]
Yup!

**Comment by MeoMix** [comment]
Closing. These will all play in the new version (if/when that makes it live) since it's using YouTube.com instead of self-hosting.
