### ISSUE TITLE
Space bar play/pause behavior is unpredictable in tab mode

### ISSUE THREAD

**Issue by Vadskye** [MeoMix/StreamusChromeExtension#609]
When switching to an existing Streamus tab, space bar can be used to play/pause the music. This is useful, and I appreciate it. However, when opening a new Streamus tab, the cursor is set to the search bar. Therefore, pressing space bar simply inserts a single space into the search window, which is useless.

I understand why the cursor is placed into the search bar by default; that's a useful feature. However, I don't think there is any normal use case where a user would intend to begin their search with a single space. Would it be feasible to capture space bar input at the beginning of the search, and use it to play/pause?

**Comment by MeoMix** [comment]
Makes sense. Will keep it in mind. Streamus isn't even on the Chrome
Web Store at the moment so I have bigger fish to fry for now.

**Comment by Vadskye** [comment]
Oh! Yes, this is definitely low priority. Good luck!
