### ISSUE TITLE
No related songs found

### ISSUE THREAD

**Issue by idmontie** [MeoMix/StreamusChromeExtension#612]
The radio feature stopped working for me. When the last song in the playlist is done playing, or I click the next song button, nothing happens. I looked at the console and I did get an uncaught error:

```
Uncaught Error: No related songs found
```

Followed by the JSON object of the sounds in the queue. It doesn't matter if I have 1 song in the queue or many songs, I still do not get any related songs.

Any idea if this is a bug on my end (maybe too many Youtube requests?) or a bug somewhere else in the code?

**Comment by MeoMix** [comment]
YouTube has presumably revoked Streamus' API key as they noted they
would at 5PM on Friday for non-compliance issues.

**Comment by idmontie** [comment]
Oh no! So we can only play songs that we have already added to our playlists? It looks like we can't search either. Bummer. I guess I can use developer mode + my own API key? Did you ever find out if playing the Youtube video in the tab view would suffice?

EDIT: Closing since this is not an issue with StreamusChromeExtension

**Comment by MeoMix** [comment]
I suspect it will suffice, but YouTube has ceased communicating with me so I'm just going to have to upload it and find out. It's kind of stupid.

**Comment by idmontie** [comment]
I feel for you, all of that work separating and decoding the music from the video is going to be for naught. Good luck, hopefully I'll have time this weekend to delve into your code.
