### ISSUE TITLE
Add to streamus from YouTube doesn't work

### ISSUE THREAD

**Issue by yotamN** [MeoMix/StreamusChromeExtension#613]
I want to add songs and I can't it's show me a notification that there is an error

**Comment by MeoMix** [comment]
That's because YouTube has revoked Streamus' API key. It won't work for a few weeks until I can fix ToS issues... read the announcement that pops up when using Streamus pls.

**Comment by yotamN** [comment]
Oh sorry, but didn't you changed the extension so it's would be legal?

**Comment by MeoMix** [comment]
I did and they decided it still wasn't sufficient. They wanted me to pause the music whenever the extension's popup window minimizes... which would make Streamus completely useless.

**Comment by yotamN** [comment]
I think I will start read the code and will add a way to add a video by it id for now

**Comment by MeoMix** [comment]
Well... to turn a video ID into video data you have to query YouTube's servers: https://github.com/MeoMix/StreamusChromeExtension/blob/Development/src/js/background/model/youTubeV3API.js#L107

But this requires using an API key and the account for Streamus isn't allowed to make API requests currently.

**Comment by yotamN** [comment]
I only used YouTube API a little but can't you just use an iframe? Like getting the id and then doing something like this:

```
var song = `<iframe width="560" height="315" src="https://www.youtube.com/embed/${id}" frameborder="0" allowfullscreen></iframe>`;
```

**Comment by MeoMix** [comment]
That's what Streamus does to load the song for playback. Playback of a song works fine and doesn't rely on YouTube's API. But, getting the song's duration, title, related songs for radio mode, etc.. all rely on YouTube's API.
