### ISSUE TITLE
Foreground CSS is missing

### ISSUE THREAD

**Issue by bitsmanent** [MeoMix/StreamusChromeExtension#614]
Hi,

I'm trying to load Streamus as unpackaged extension, I set my API key and it works. Though the extension is unusable due to the fact that the /css/foreground.css file is missing. Please, git add it. Thanks!

**Comment by Magentah** [comment]
The css is not compiled from the less files when you download the source, you need to compile to less files. There are instructions on how in the README.md that's viewable on the github page, just above the API Key section.

**Comment by bitsmanent** [comment]
Sorry, my fault. Thanks!
