### ISSUE TITLE
Cannot read property 'getExposedProperties' of undefined

### ISSUE THREAD

**Issue by daniel-1981** [MeoMix/StreamusChromeExtension#615]
I'm trying to execute your code in Chrome (using developer mode) but i see this error inside console of Developer Tools

js/foreground/plugins.js:17
Uncaught TypeError: Cannot read property 'getExposedProperties' of undefined

and I only see blank chart.

Can you help me to solve this problem?

**Comment by MeoMix** [comment]
You'll want to inspect background.html on chrome://extensions. It failed to load properly and there's probably an error on that page.

**Comment by daniel-1981** [comment]
You are a master MeoMix!!!. I had copied file youTubeAPIKey.js.example and then renamed it to youTubeAPIKey.js but I didn't delete original, so I believe that  was my error. Now, how i can block youtube video player? Thanks in advance :)

**Comment by MeoMix** [comment]
Go to VideoRegion.js and comment out hiding the view. :)

**Comment by MeoMix** [comment]
showing*

**Comment by daniel-1981** [comment]
Thanks a lot again MeoMix. I'll close this issue :)
