### ISSUE TITLE
Migrate to being a webpage?

### ISSUE THREAD

**Issue by hdavidzhu** [MeoMix/StreamusChromeExtension#616]
Now that the Chrome extension version is no longer possible, would Youtube also dislike a website?

For instance, I use this service: http://listenonrepeat.com/
The video is always displaying, but I still use it to listen to music on repeat.

A complete website would also offer the video to always be playing and still not be that annoying. And it's still better than the current Youtube playlist feature. Since the extension is also Javascript, the port wouldn't be too hard.

**Comment by Magentah** [comment]
Streamus already offered an option to use a tab, YouTube didn't like it. Using their API they wanted the video to pause when you navigated to a different tab, regardless of if the video was always displaying within the tab.

**Comment by hdavidzhu** [comment]
What about just Youtube embeds? I made a prototype of it before:
http://youtrello.herokuapp.com/?#/room/cat
(Searching is now broken for some reason, but the concept might be possible). I'm guessing the radio feature depends on the API?

**Comment by Magentah** [comment]
YouTube's stance seems to be that any site/app/extension that plays content from YouTube needs to pause when the video isn't in view.
