### ISSUE TITLE
no results found for all searches

### ISSUE THREAD

**Issue by brenovieira** [MeoMix/StreamusChromeExtension#625]
Everything I search for is getting "no results found".

Some examples:
![image](https://cloud.githubusercontent.com/assets/7158650/11217681/b5e4d1f0-8d38-11e5-82af-e781ac29afa4.png)

![image](https://cloud.githubusercontent.com/assets/7158650/11217724/ea4e737e-8d38-11e5-96a0-6282d71aa0b9.png)

I have a saved playlist, but I can't add other videos as I don't find anything:
![image](https://cloud.githubusercontent.com/assets/7158650/11217804/43ca69da-8d39-11e5-97d4-df19e536537d.png)

Using version:
![image](https://cloud.githubusercontent.com/assets/7158650/11217739/fe2c3be2-8d38-11e5-8473-1e59b6250666.png)

Chrome version:
![image](https://cloud.githubusercontent.com/assets/7158650/11217762/1be1215c-8d39-11e5-98e7-8e238c92594c.png)

**Comment by MeoMix** [comment]
http://thenextweb.com/insider/2015/07/21/how-youtube-killed-an-extension-with-300000-users/

You'd need to provide your own YouTube API Key found in background/keys/youtubeApi

**Comment by brenovieira** [comment]
@MeoMix , I'm sorry. I didn't know this.

I will try to use my api key :+1:
